### ISSUE TITLE
Cannot read property 'fetchUsers' of undefined.

### ISSUE THREAD

**Issue by Xge21** [shukriadams/discord-giveawaybot#16]
The Bot isn't stopping a giveaway and spam this in console:

```
error:  TypeError: Cannot read property 'fetchUsers' of undefined
    at /broady/myBot/lib/reactionHelper.js:16:58
    at new Promise (<anonymous>)
    at Object.getAllReactionUsers (/broady/myBot/lib/reactionHelper.js:7:12)
    at Daemon.tick (/broady/myBot/lib/daemon.js:151:59)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by shukriadams** [comment]
Yes, I disabled the null check there. I re-activated it in https://github.com/shukriadams/discord-giveawaybot/releases/tag/0.1.8. Assuming this issue is closed now, feel free to re-open if it isn't resolved.
