### ISSUE TITLE
Unknown Emoji

### ISSUE THREAD

**Issue by Xge21** [shukriadams/discord-giveawaybot#17]
```
error:  DiscordAPIError: Unknown Emoji
    at item.request.gen.end (/myBot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
    at then (/myBot/node_modules/snekfetch/src/index.js:215:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
{ DiscordAPIError: Unknown Emoji
    at item.request.gen.end (/myBot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
    at then (/myBot/node_modules/snekfetch/src/index.js:215:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'DiscordAPIError',
  message: 'Unknown Emoji',
  path:
   '/api/v7/channels/490892207486795786/messages/490970498511929394/reactions/%3Asmile%3A/@me',
  code: 10014 }

```

**Comment by Xge21** [comment]
settings.json:
```
{
  "token": "******************************************************************************",
  "joinGiveawayResponseCharacter": ":hand_splayed:",
  "giveawayRole": "********",
  "bracketsCurrencyZone": "us",
  "daemonInterval": "*/10 * * * * *",
  "maxConcurrentGiveaways": 5,
  "winningCooldownDays": 3,
  "deleteGiveawaysAfter": 1,
  "processLifetime": 10,
  "guildId": "**********************",
  "giveawayChannelId": "************************"
}

```

**Comment by shukriadams** [comment]
This error is likely caused by you using a string to represent your emoji, instead of an actual ASCII emoji character. For example, the default emoji is 🎉, and not ":fanfare:". You're using ":hand_splayed:", check out a site like https://getemoji.com, find the emoji you want there, and put that imagey character into your settings.json. This is a limitation of discord's api I'm afraid.
